name: Building & Testing

on:
  push:
    branches: [ master, zhi/github-action ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      matrix:
        ros_distributions: 
          - melodic
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup ROS
        uses: ros-tooling/setup-ros@0.0.20
        with: 
          required-ros-distributions: ${{ matrix.ros_distributions }}
      - name: Create Workspace
        run: "mkdir -p ros_ws/src"  
      - uses: actions/checkout@v2
        with:
          path: ros_ws/src/tbd_screen_face
      - name: Install Dependencies
        run: |
          source /opt/ros/${{matrix.ros_distributions}}/setup.bash
          rosdep update
          rosdep install -i --from-paths ros_ws/src
      - name: Catkin Build
        run: |
          source /opt/ros/${{matrix.ros_distributions}}/setup.bash
          cd src/tbd_screen_face
          catkin run_tests this